
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-8">
	    <table>
		    <thead>
		    	<tr><th>שם</th><th>תכונות</th><th>דרגה</th><th>נרשם</th><th>פנוי</th></tr>
		    </thead>
		    <tbody class="table-striped table-hover">
		    	<tr><td>יוני מנדס</td><td>
		    	<ul class="player-attributes list-inline">
		    		<li class="hospitality">5</li>
		    		<li class="loyalty">5</li>
		    		<li class="mobility">5</li>
		    		<li class="teamplay">5</li>
		    		<li class="rules">5</li>
		    		<li class="humor">5</li>
		    	</ul>
		    	</td><td>5 (שחקן מנוסה, שחקן אמיתי, קבוצתי)</td><td>לפני שנה</td><td>כן, מחפש קבוצה להנחות</td></tr>
		    </tbody>
	    </table>
    </div>
</div>
