
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-8">
	    <table>
		    <thead>
		    	<tr><th>שם</th><th>גיל</th><th>תכונות</th><th>טיפוס/דרגה</th><th>נרשם</th><th>פנוי</th></tr>
		    </thead>
		    <tbody class="table-striped table-hover">
		    	<tr><td>יוני מנדס</td><td>35 שנות אדם</td><td>
		    	<ul class="player-attributes list-inline no-list-indent">
		    		<li class="hospitality" rating="5">5</li>
		    		<li class="mobility" rating="5">5</li>
		    		<li class="teamplay" rating="5">5</li>
		    		<li class="rules" rating="5">5</li>
		    		<li class="humor" rating="5">5</li>
		    	</ul>
		    	</td><td>5 (שחקן מנוסה, תפקידיסט אמיתי, קבוצתי)</td><td>לפני שנה</td><td>כן, מחפש קבוצה להנחות</td></tr>
		    </tbody>
	    </table>
    </div>
</div>
<script>

var tips = {};
$(function(){
	$.get('/tips', '', function(data){
		$.each(data, function(index, item){
			if (typeof tips[item.attribute] == 'undefined') {
				tips[item.attribute] = {};
			}
			tips[item.attribute][item.rating] = item;
		});
	});
});


  $(function() {
    jQuery.each($( '.player-attributes li' ), function(key, item) {
        var attribute = $(item).attr('class');
        var attrValue = $(item).attr('rating');

        $(item).tooltip({
	      position: {
	        my: "right top+10",
	        at: "right+35 bottom",
	        using: function( position, feedback ) {
	          $( this ).css( position );
	          $( "<div>" )
	            .addClass( "arrow " + $(item).attr('class') )
	            .addClass( feedback.vertical )
	            .addClass( feedback.horizontal )
	            .appendTo( this );
	        },
	      },
	      items: "li",
	      content: function() {
		      var tip = tips[attribute][attrValue];
	            return "<blockquote>\
	            <p class=\"" + attribute + "\">" + tip.quote + "</p>\
	            <small>"+tip.description+"</small>\
	          </blockquote>";
	        },
	      tooltipClass: $(item).attr('class')
    	});

        /* $(item).on('tooltipclose', function( event, ui ) {
        	console.log(this,event,ui);
        	$(this).tooltip('open');
        } ); */
    });
  });
  </script>