	<div class="row show-grid">
		<div class="col-md-4 theme-style">
			<!-- Thumbnails -->
			<div class="thumbnail">
			<h3 class="text-center">יוני מנדס</h3>
				<img src="http://www.gravatar.com/avatar/<?php echo md5(trim('yonmanm@gmail.com')) ?>?s=200" />
				<ul class="list-group custom-set">
					<li class="list-group-item"><span class="teamplay attribute-icon">5</span>&nbsp;<label>חברותי</label></li>
					<li class="list-group-item"><span class="humor attribute-icon">4</span>&nbsp;<label>הומור</label></li>
					<li class="list-group-item"><span class="hospitality attribute-icon">4</span>&nbsp;<label>אירוח</label></li>
					<li class="list-group-item"><span class="mobility attribute-icon">4</span>&nbsp;<label>ניידות</label></li>
					<li class="list-group-item"><span class="rules attribute-icon">4</span>&nbsp;<label>גמישות</label></li>
				</ul>
			</div><!-- /Thumbnails -->		
		</div>
		<div class="col-md-8 left-block">
			<div class="info-block">
				<div class="info-text">
					<p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית סחטיר בלובק. תצטנפל בלינדו למרקל אס לכימפו, דול, צוט ומעיוט - לפתיעם ברשג - ולתיעם גדדיש. קוויז דומור ליאמום בלינך רוגצה. לפמעט מוסן מנת. מוסן מנת. להאמית קרהשק סכעיט דז מא, מנכם למטכין נשואי מנורך. ושבעגט ליבם סולגק. בראיט ולחת צורק מונחף, בגורמי מגמש. תרבנך וסתעד לכנו סתשם השמה - לתכי מורגם בורק? לתיג ישבעס.</p>
					<p>צש בליא, מנסוטו צמלח לביקו ננבי, צמוקו בלוקריה שיצמה ברורק. קולורס מונפרד אדנדום סילקוף, מרגשי ומרגשח. עמחליף לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. נולום ארווס סאפיאן - פוסיליס קוויס, אקווזמן קוואזי במר מודוף. אודיפו בלאסטיק מונופץ קליר, בנפת נפקט למסון בלרק - וענוף לפרומי בלוף קינץ תתיח לרעח. לת צשחמי הועניב היושבב שערש שמחויט - שלושע ותלברו חשלו שעותלשך וחאית נובש ערששף. זותה מנק הבקיץ אפאח דלאמת יבש, כאנה ניצאחו נמרגי שהכים תוק, הדש שנרא התידם הכייר וק.</p>
					
				</div>
				<ul class="social-icon ltr-only">
					<li><a href="" class="social twitter">@ZendSui</a></li>
					<li><a href="" class="social google_plus">yonmanm</a></li>
					<li><a href="" class="social facebook">YonmaN</a></li>
					<li><a href="" class="social skype">yonmanm</a></li>
				</ul>
				<div class="list">
					<ul class="list-group inverse-theme">
						<li class="list-group-item"><h4>Sales Summary</h4></li>
						<li class="list-group-item"><span class="badge">19</span>Today Sold</li>
						<li class="list-group-item"><span class="badge">35</span>Weekly Sales</li>
						<li class="list-group-item"><span class="badge">1989</span>Total Sold</li>
					</ul>
				</div>
			</div>
			<nav role="navigation" class="navbar navbar-default">
				<ul class="nav nav-pills">
					<li class="active"><a href="#">Latest Customers</a></li>
					<li><a href="#">Feeds</a></li>
				</ul>
			</nav>
			<div class="content-text">
				<table class="table table-striped table-hover">
					<thead>
					  <tr>
						<th>Company</th>
						<th>Descrition</th>
						<th>Amount</th>
					  </tr>
					</thead>
					<tbody>
					  <tr>
						<td>Smart House</td>
						<td>Office furniture purchase</td>
						<td>$52560.10</td>
					  </tr>
					  <tr>
						<td>Smart House</td>
						<td>Office furniture purchase</td>
						<td>$52560.10</td>
					  </tr>
					  <tr>
						<td>Smart House</td>
						<td>Office furniture purchase</td>
						<td>$52560.10</td>
					  </tr>
					  <tr>
						<td>Smart House</td>
						<td>Office furniture purchase</td>
						<td>$52560.10</td>
					  </tr>
					  <tr>
						<td>Smart House</td>
						<td>Office furniture purchase</td>
						<td>$52560.10</td>
					  </tr>
					</tbody>
				</table>
				<article>
					<h3>Sed diam nonummy nibh euismod</h3>
					<p>Proin vitae volutpat tellus. Fusce erat libero, ultrices in egestas id, tincidunt quis ante. Nam volutpat purus sed justo hendrerit, ac pellentesque odio volutpat. Integer vitae purus tortor. Aenean <a href="#">ultricies porta</a> rhoncus. Nullam eleifend, tortor quis porta consectetur, enim nunc rutrum erat, ut convallis augue libero ac orci.</p>
					<p>Aenean ultricies porta rhoncus eleifend tortor quis.</p>
				</article>
			</div>				
		</div>
	</div>

    <div>
    http://wrapbootstrap.com/preview/WB0P6MJ29
    תכונות
    אזורים למשחק
    מערכות
    סוגי משחקים
    לינקים חיצוניים?
    דרגה
    תגיות
    מחפש קבוצה
    יצירת קשר
    </div>
