	<div class="row show-grid">
		<div class="col-md-5 col-lg-4">
			<div class="left-block">
				<div class="row">
					<div id="banner-name" class="thumbnail col-md-12 col-xs-4">
						<h2 class="text-center">יוני מנדס</h2>
						<img src="http://www.gravatar.com/avatar/<?php echo md5(trim('yonmanm@gmail.com')) ?>?s=200" />
					</div>
					<div id="attributes-list" class="col-md-4 col-xs-3 info-block">
						<h4>תכונות</h4>
						<ul class="list-group custom-set">
							<li class="list-group-item"><span class="teamplay attribute-icon">5</span>&nbsp;<label>חברותי</label></li>
							<li class="list-group-item"><span class="humor attribute-icon">4</span>&nbsp;<label>הומור</label></li>
							<li class="list-group-item"><span class="hospitality attribute-icon">4</span>&nbsp;<label>אירוח</label></li>
							<li class="list-group-item"><span class="mobility attribute-icon">4</span>&nbsp;<label>ניידות</label></li>
							<li class="list-group-item"><span class="rules attribute-icon">4</span>&nbsp;<label>גמישות</label></li>
						</ul>
					</div>
					<div class="col-md-8 col-xs-5 info-block">
						<h4>מחפש קבוצה</h4>
						<ul class="badge-list list-group inverse-theme">
							<li class="list-group-item"><span class="badge">מנחה</span>להיות מנחה</li>
							<li class="list-group-item"><span class="badge">שחקן</span>להצטרף לקבוצה</li>
						</ul>
						<h4>תגיות</h4>
						<p class="">שחקן דומיננטי, Real Roleplayer, תיאוריסט</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-7 col-lg-8 left-block">
			<div class="info-block">
				<div class="info-text">
					<p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית סחטיר בלובק. תצטנפל בלינדו למרקל אס לכימפו, דול, צוט ומעיוט - לפתיעם ברשג - ולתיעם גדדיש. קוויז דומור ליאמום בלינך רוגצה. לפמעט מוסן מנת. מוסן מנת. להאמית קרהשק סכעיט דז מא, מנכם למטכין נשואי מנורך. ושבעגט ליבם סולגק. בראיט ולחת צורק מונחף, בגורמי מגמש. תרבנך וסתעד לכנו סתשם השמה - לתכי מורגם בורק? לתיג ישבעס.</p>
					<p>צש בליא, מנסוטו צמלח לביקו ננבי, צמוקו בלוקריה שיצמה ברורק. קולורס מונפרד אדנדום סילקוף, מרגשי ומרגשח. עמחליף לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. נולום ארווס סאפיאן - פוסיליס קוויס, אקווזמן קוואזי במר מודוף. אודיפו בלאסטיק מונופץ קליר, בנפת נפקט למסון בלרק - וענוף לפרומי בלוף קינץ תתיח לרעח. לת צשחמי הועניב היושבב שערש שמחויט - שלושע ותלברו חשלו שעותלשך וחאית נובש ערששף. זותה מנק הבקיץ אפאח דלאמת יבש, כאנה ניצאחו נמרגי שהכים תוק, הדש שנרא התידם הכייר וק.</p>
					
				</div>
				<ul class="social-icon">
					<li><a href="" class="social ltr-only twitter">@ZendSui</a></li>
					<li><a href="" class="social google_plus">yonmanm</a></li>
					<li><a href="" class="social facebook">YonmaN</a></li>
					<li><a href="" class="social skype">yonmanm</a></li>
				</ul>
			</div>
			<ul class="content-text list-inline">
				<li class=""><h4>גאוגרפיה:</h4></li>
				<li class=""><span class="badge">אזור: המרכז</span></li>
				<li class=""><span class="badge">אזור: השרון</span></li>
				<li class=""><span class="badge">מישור: אינטרנט</span></li>
			</ul>
			<ul class="content-text list-inline">
				<li><h4>ג'אנרים:</h4></li>
				<li><span class="badge">אימה</span></li>
				<li><span class="badge">High Fantasy</span></li>
				<li><span class="badge">אלים וגיבורים</span></li>
				<li><span class="badge">דיסטופיה</span></li>
				<li><span class="badge">גיבורי על</span></li>
			</ul>
			<ul class="content-text list-inline">
				<li><h4>משחקים:</h4></li>
				<li><span class="badge">AD&D 2nd ed</span></li>
				<li><span class="badge">D&D 3.5</span></li>
				<li><span class="badge">Exalted 2nd</span></li>
				<li><span class="badge">Shadow Run 5th</span></li>
				<li><span class="badge">PDQ</span></li>
				<li><span class="badge">Wushu</span></li>
			</ul>
		</div>
 	</div>

    <div>
    http://wrapbootstrap.com/preview/WB0P6MJ29
    תכונות
    אזורים למשחק
    מערכות
    סוגי משחקים
    לינקים חיצוניים?
    דרגה
    תגיות
    מחפש קבוצה
    יצירת קשר
    </div>
